name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
      - name: Install Dependencies
        run: npm i
      - name: Copy env
        run: cp env.example.js env.js
      - name: Run Build
        run: npm run build
